---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml
    - vars/vars-homebrew.yml
    - vars/vars-dotfiles.yml
    - vars/vars-dockutil.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - dhellmann.python-dev

#    - fubarhouse.sublime

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
    - include: tasks/dockutil.yml
      when: '"dockutil" in homebrew_installed_packages'
    
    - name: Run .osx dotfiles.
      shell: ~/.osx --no-restart
      changed_when: false
      when: '".osx" in dotfiles_files'
