---
- hosts: localhost
  strategy: free
  connection: local

  vars_files:
    - vars/main.yml
    - vars/vars-homebrew.yml
    - vars/vars-dockutil.yml

  roles:
    #- geerlingguy.homebrew
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    #- geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/main.yml
#    - include: tasks/preferences.yml
    - include: tasks/dockutil.yml
      when: '"dockutil" in homebrew_installed_packages'
  
    - name: Run .osx dotfiles.
      shell: "{{ osx_script }}"
      changed_when: false
